#!/usr/bin/env python3
"""
OSINT Tool - Cybersecurity Intelligence Gathering
Author: Generated by Superagent
"""

import sys
import socket
import ssl
import json
import re
import itertools
import urllib.request
import urllib.parse
import urllib.error
from datetime import datetime

try:
    import whois
    WHOIS_AVAILABLE = True
except ImportError:
    WHOIS_AVAILABLE = False

try:
    import dns.resolver
    DNS_AVAILABLE = True
except ImportError:
    DNS_AVAILABLE = False

# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def print_section(title):
    print(f"\n{'='*55}")
    print(f"  {title}")
    print(f"{'='*55}")

def safe_get(url, timeout=8):
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (OSINT-Tool)"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.read().decode("utf-8", errors="ignore"), dict(resp.headers)
    except Exception as e:
        return None, {}

# ─────────────────────────────────────────────
# 1. WHOIS
# ─────────────────────────────────────────────

def get_whois(domain):
    print_section("WHOIS INFO")
    if not WHOIS_AVAILABLE:
        print("  [!] whois module not installed. Run: pip install python-whois")
        return {}
    try:
        w = whois.whois(domain)
        info = {}
        fields = ["domain_name","registrar","creation_date","expiration_date",
                  "updated_date","name_servers","status","emails","name","org",
                  "address","city","state","zipcode","country"]
        for f in fields:
            val = getattr(w, f, None)
            if val:
                info[f] = str(val)
                print(f"  {f:20}: {str(val)[:80]}")
        return info
    except Exception as e:
        print(f"  [!] WHOIS error: {e}")
        return {}

# ─────────────────────────────────────────────
# 2. DNS
# ─────────────────────────────────────────────

def get_dns(domain):
    print_section("DNS RECORDS")
    results = {}
    if DNS_AVAILABLE:
        for rtype in ["A","AAAA","MX","NS","TXT","CNAME","SOA"]:
            try:
                answers = dns.resolver.resolve(domain, rtype)
                vals = [str(r) for r in answers]
                results[rtype] = vals
                print(f"  {rtype:6}: {', '.join(vals)[:100]}")
            except Exception:
                pass
    else:
        # fallback: basic socket
        try:
            ip = socket.gethostbyname(domain)
            results["A"] = [ip]
            print(f"  A     : {ip}")
        except Exception as e:
            print(f"  [!] DNS error: {e}")
    return results

# ─────────────────────────────────────────────
# 3. HTTP Headers & Tech Detection
# ─────────────────────────────────────────────

def get_http_info(url):
    print_section("HTTP HEADERS & TECH")
    body, headers = safe_get(url)
    if not headers:
        print("  [!] Could not reach the URL.")
        return {}, ""

    interesting = ["Server","X-Powered-By","X-Generator","X-Frame-Options",
                   "Content-Security-Policy","Strict-Transport-Security",
                   "X-Content-Type-Options","Set-Cookie","Location",
                   "X-AspNet-Version","CF-Ray","Via"]
    for h in interesting:
        val = headers.get(h) or headers.get(h.lower())
        if val:
            print(f"  {h:30}: {val[:100]}")

    # CMS detection
    techs = []
    if body:
        patterns = {
            "WordPress": r"wp-content|wp-includes|wordpress",
            "Joomla":    r"joomla",
            "Drupal":    r"drupal",
            "Shopify":   r"shopify",
            "React":     r"react\.js|react-dom|__REACT",
            "Vue.js":    r"vue\.js|vue\.min\.js",
            "Angular":   r"ng-version|angular\.js",
            "Bootstrap": r"bootstrap\.min\.css|bootstrap\.css",
            "jQuery":    r"jquery\.min\.js|jquery-",
        }
        for tech, pat in patterns.items():
            if re.search(pat, body, re.IGNORECASE):
                techs.append(tech)
        if techs:
            print(f"\n  [+] Detected technologies: {', '.join(techs)}")

    return headers, body or ""

# ─────────────────────────────────────────────
# 4. Metadata & Personal Info Extraction
# ─────────────────────────────────────────────

def extract_metadata(url, body):
    print_section("METADATA & PERSONAL INFO")
    person_data = {}

    if not body:
        print("  [!] No body to analyze.")
        return person_data

    # emails
    emails = list(set(re.findall(r'[\w\.-]+@[\w\.-]+\.\w{2,6}', body)))
    if emails:
        person_data["emails"] = emails
        print(f"  Emails found    : {', '.join(emails[:10])}")

    # phone numbers
    phones = list(set(re.findall(r'[\+\(]?[\d\s\-\(\)]{7,20}[\d]', body)))
    phones = [p.strip() for p in phones if len(re.sub(r'\D','',p)) >= 7][:10]
    if phones:
        person_data["phones"] = phones
        print(f"  Phones found    : {', '.join(phones[:5])}")

    # social media
    socials = {}
    social_patterns = {
        "twitter":   r'twitter\.com/([A-Za-z0-9_]{1,50})',
        "linkedin":  r'linkedin\.com/in/([A-Za-z0-9\-]{1,80})',
        "instagram": r'instagram\.com/([A-Za-z0-9_\.]{1,50})',
        "facebook":  r'facebook\.com/([A-Za-z0-9\.]{1,80})',
        "github":    r'github\.com/([A-Za-z0-9\-]{1,40})',
        "youtube":   r'youtube\.com/(?:c/|channel/|user/)?([A-Za-z0-9_\-]{1,80})',
    }
    for net, pat in social_patterns.items():
        matches = re.findall(pat, body, re.IGNORECASE)
        if matches:
            socials[net] = list(set(matches))
            print(f"  {net:12}: {', '.join(socials[net][:3])}")
    if socials:
        person_data["social_media"] = socials

    # meta tags
    meta_patterns = {
        "author":      r'<meta[^>]+name=["\']author["\'][^>]+content=["\'](.*?)["\']',
        "description": r'<meta[^>]+name=["\']description["\'][^>]+content=["\'](.*?)["\']',
        "keywords":    r'<meta[^>]+name=["\']keywords["\'][^>]+content=["\'](.*?)["\']',
        "og:title":    r'<meta[^>]+property=["\']og:title["\'][^>]+content=["\'](.*?)["\']',
        "og:site_name":r'<meta[^>]+property=["\']og:site_name["\'][^>]+content=["\'](.*?)["\']',
    }
    for key, pat in meta_patterns.items():
        m = re.search(pat, body, re.IGNORECASE | re.DOTALL)
        if m:
            person_data[key] = m.group(1).strip()
            print(f"  {key:16}: {m.group(1).strip()[:80]}")

    # names from body
    name_matches = re.findall(
        r'\b([A-Z][a-z]{2,15})\s([A-Z][a-z]{2,15})\b', body)
    if name_matches:
        names = list(set([f"{a} {b}" for a,b in name_matches]))[:5]
        person_data["possible_names"] = names
        print(f"  Possible names  : {', '.join(names)}")

    # dates / years
    years = list(set(re.findall(r'\b(19[5-9]\d|20[0-2]\d)\b', body)))
    if years:
        person_data["years_found"] = years
        print(f"  Years found     : {', '.join(sorted(years)[:10])}")

    return person_data

# ─────────────────────────────────────────────
# 5. Password Generator
# ─────────────────────────────────────────────

LEET = {'a':'4','e':'3','i':'1','o':'0','s':'5','t':'7'}

def leet(word):
    result = ""
    for c in word.lower():
        result += LEET.get(c, c)
    return result

def generate_passwords(person_data, domain):
    print_section("GENERATED PASSWORDS (OSINT-BASED)")

    tokens = set()

    # domain name parts
    base_domain = domain.replace("www.","").split(".")[0]
    tokens.add(base_domain)

    # emails → extract name parts
    for email in person_data.get("emails", []):
        local = email.split("@")[0]
        for part in re.split(r'[._\-]', local):
            if len(part) > 2:
                tokens.add(part)

    # possible names
    for full_name in person_data.get("possible_names", []):
        parts = full_name.split()
        for p in parts:
            tokens.add(p.lower())
        tokens.add(full_name.replace(" ","").lower())
        tokens.add(full_name.replace(" ","_").lower())

    # author meta
    author = person_data.get("author","")
    if author:
        for p in author.split():
            tokens.add(p.lower())

    # years
    years = person_data.get("years_found", [])

    # og:title / site_name
    for key in ["og:title","og:site_name","description"]:
        val = person_data.get(key,"")
        if val:
            words = re.findall(r'[A-Za-z]{3,12}', val)
            for w in words[:4]:
                tokens.add(w.lower())

    tokens.discard("")

    suffixes = ["", "123", "1234", "12345", "!", "@", "#", "2024", "2025",
                "2023", "01", "99", "00", "007", "!@#"]
    prefixes = ["", "admin", "pass", "P@ss"]

    passwords = set()

    for tok in list(tokens)[:15]:
        for suf in suffixes[:8]:
            passwords.add(tok + suf)
            passwords.add(tok.capitalize() + suf)
            passwords.add(leet(tok) + suf)
        for pre in prefixes[1:3]:
            passwords.add(pre + tok.capitalize())

        # tok + year combos
        for yr in years[:3]:
            passwords.add(tok + yr)
            passwords.add(tok.capitalize() + yr)

    # domain + year
    for yr in years[:3]:
        passwords.add(base_domain + yr)
        passwords.add(base_domain.capitalize() + yr)

    # sort by likely strength (longer first)
    password_list = sorted(passwords, key=lambda x: -len(x))[:50]

    print(f"\n  Generated {len(password_list)} candidate passwords:\n")
    for i, pw in enumerate(password_list, 1):
        print(f"  {i:3}. {pw}")

    return password_list

# ─────────────────────────────────────────────
# 6. Export
# ─────────────────────────────────────────────

def export_report(domain, whois_data, dns_data, person_data, passwords):
    filename = f"osint_{domain.replace('.','_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    report = {
        "target": domain,
        "date": datetime.now().isoformat(),
        "whois": whois_data,
        "dns": dns_data,
        "metadata": person_data,
        "generated_passwords": passwords,
    }
    with open(filename, "w") as f:
        json.dump(report, f, indent=2, default=str)
    print(f"\n  [+] Report saved to: {filename}")
    return filename

# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main():
    print("╔══════════════════════════════════════════════════════╗")
    print("║          OSINT TOOL — Cybersecurity Edition          ║")
    print("║       For authorized security testing only           ║")
    print("╚══════════════════════════════════════════════════════╝")

    if len(sys.argv) > 1:
        raw_url = sys.argv[1]
    else:
        raw_url = input("\n  [?] Enter target URL: ").strip()

    # normalize
    if not raw_url.startswith("http"):
        raw_url = "https://" + raw_url

    parsed = urllib.parse.urlparse(raw_url)
    domain = parsed.netloc or parsed.path
    domain = domain.replace("www.","")
    url    = raw_url

    print(f"\n  Target  : {url}")
    print(f"  Domain  : {domain}")
    print(f"  Started : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    whois_data  = get_whois(domain)
    dns_data    = get_dns(domain)
    _, body     = get_http_info(url)
    person_data = extract_metadata(url, body)
    passwords   = generate_passwords(person_data, domain)
    report_file = export_report(domain, whois_data, dns_data, person_data, passwords)

    print(f"\n{'='*55}")
    print(f"  ✅ OSINT scan complete!")
    print(f"  Report: {report_file}")
    print(f"{'='*55}\n")

if __name__ == "__main__":
    main()
